export const civic = {
  bg: '#f3f5f8',
  bgSoft: '#f7f9fb',
  surface: '#ffffff',
  navy: '#0b1f3a',
  navySoft: '#163356',
  teal: '#0d7a6f',
  tealHover: '#0a635a',
  tealSoft: '#e6f4f2',
  tealMuted: '#f0f9f8',
  muted: '#5b6b7c',
  muted2: '#8fa0b3',
  border: '#d8e0ea',
  borderHover: '#b8c6d6',
  track: '#eef2f6',
  amberBg: '#f8f1e4',
  amberText: '#8a5a10',
  amberBorder: '#f0e0c4',
  danger: '#dc2626',
  dangerBg: '#fef2f2',
  dangerBorder: '#fecaca',
  success: '#047857',
  successBg: '#ecfdf5',
  successBorder: '#a7f3d0',
  purple: '#6b21a8',
  purpleBg: '#faf5ff',
  purpleBorder: '#e9d5ff',
  white: '#ffffff',
  overlay: 'rgba(11, 31, 58, 0.45)',
};

export const civicShadow = {
  card: {
    shadowColor: '#0b1f3a',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  raised: {
    shadowColor: '#0b1f3a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 18,
    elevation: 6,
  },
  toast: {
    shadowColor: '#0d7a6f',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 8,
  },
};
